name = "ORIME"
license = ""
licenselink = ""
description = ""
homepage = "https://blog.umeru.ma/"
tags = []
features = []
min_version = "0.41"

[author]
  name = "umeruma"
  homepage = "https://umeru.ma/"

